### ISSUE TITLE
Adding Location and Image type response from telegram bot

### ISSUE THREAD

**Issue by AliAyub007** [fossasia/susi_telegrambot#10]
**Actual Behaviour**

Currently telegram bot is not returning location type response and neither images type response 

**Expected Behaviour**

Telegram bot should return location type response in form of map and images type response in form of images.

**Steps to reproduce it**

I will use location type and image type to send response using 

**Screenshots of expected outcome**

![18947135_816279961856446_1760968069_o](https://cloud.githubusercontent.com/assets/25840461/26768254/17311686-49c0-11e7-9932-af59ee8b5432.png)

**Would you like to work on the issue?**

Yes

**Comment by Manveer695** [comment]
I think you should write screenshots after the issue was resolved, above in the description.
