### ISSUE TITLE
Loop through action types and display result for all actions

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_telegrambot#12]
**Actual Behaviour**

Query "multi3". The sever response contains 3 action types but only result of first is displayed.
Also for map type only first action type is used. 

**Expected Behaviour**
```
"actions": [
      {
        "type": "answer",
        "expression": "Singapore is a place with a population of 3547809. Here is a map: https://www.openstreetmap.org/#map=13/1.2896698812440377/103.85006683126556"
      },
      {
        "type": "anchor",
        "link": "https://www.openstreetmap.org/#map=13/1.2896698812440377/103.85006683126556",
        "text": "Link to Openstreetmap: Singapore"
      },
      {
        "type": "map",
        "latitude": "1.2896698812440377",
        "longitude": "103.85006683126556",
        "zoom": "13"
      }
    ]
```
If response is of this type, then the client should loop through all the actions and display result one after other with delay provided in the response. So, ideally the result of this response should be :
* 1st message : Singapore is a place with a population of 3547809. Here is a map: https://www.openstreetmap.org/#map=13/1.2896698812440377/103.85006683126556
* 2nd message after 0 delay : [Link to Openstreetmap: Singapore](https://www.openstreetmap.org/#map=13/1.2896698812440377/103.85006683126556)
* 3rd message after 0 delay: A map displaying the given coordinates and zoom level 

For response this 
```
"actions": [
      {
        "type": "answer",
        "expression": "Line 1"
      },
      {
        "type": "answer",
        "delay": 400,
        "expression": "Line 2"
      },
      {
        "type": "answer",
        "delay": 1000,
        "expression": "Line 3"
      }
    ]
```
Response should be 
* 1st message Line 1
* 2nd message after 0.4 seconds of 1st message : Line 2
* 3rd message after 1 second of 1st message : Line 3

@AliAyub007 @Manveer695 Please create this issue in all other relevant bot repos. Thanks

**Comment by AliAyub007** [comment]
I will make response like this and will send the next commit with these conditions in the evening 👍

**Comment by AliAyub007** [comment]
@chiragw15 If we show all the three actions it gets messy due to redundancy of data in action 1 and action 2 and it looks like this :

![18838744_816574538493655_1969314416_o](https://cloud.githubusercontent.com/assets/25840461/26795090/b536707e-4a3d-11e7-91a0-c894566bf04a.png)

But If I only take 1 and 3 actions it gives all necessary information like this 

![18927151_816574541826988_1404180438_o](https://cloud.githubusercontent.com/assets/25840461/26795122/d45c2fc0-4a3d-11e7-8df7-45dc0912d0e0.png)

I think second one is better.

**Comment by chiragw15** [comment]
There is no way to decide which action to remove. Yes I know it looks a little odd now but that is the correct way to do that because if you follow this way, then there is no need for each client to change things independently. When there is a change in server, the change will automatically reflect in all the clients.This will be improved in server later on. Also second action type is anchor which means anchor the text to given link, so the user should be able to click on the text and open the link
